### ISSUE TITLE
Error in running make command

### ISSUE THREAD

**Issue by supriya-mishra** [leonwind/LSM-Tree#1]
Error given below in running make command----

/home/supriya/projects/lsmcodes/LSM-Tree/benchmark/rocksdb_benchmarks.cpp:3:10:
fatal error: rocksdb/db.h: No such file or directory
    3 | #include <rocksdb/db.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [benchmark/CMakeFiles/run_benchmarks.dir/build.make:76: benchmark/CMakeFiles/run_benchmarks.dir/benchmarks.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:170: benchmark/CMakeFiles/run_benchmarks.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by leonwind** [comment]
Hi, have you installed Rocksdb? On Ubuntu / Debian systems you can just run `sudo apt-get install librocksdb-dev`.

**Comment by supriya-mishra** [comment]
Hi,

Thanks for your reply. I will try again after installing Rocksdb and let
you know.


Best regards,
Supriya
